### ISSUE TITLE
item world npt farming items

### ISSUE THREAD

**Issue by AdamFenix** [yeetoverflow/autodisgaeaRPG#1]
im having issues with it not stopping every tenth floor to farm in item world even though i have the right boxes checked. it just runs the the whole item and onto the next one. On Blustacks 5.

**Comment by yeetoverflow** [comment]
Double check your BlueStacks settings against the [setup video](https://youtu.be/dEKeCsrjMLg) or [documentation](https://github.com/yeetoverflow/autodisgaeaRPG#setup-video). Make sure Verify button in Settings tab gives you its blessing. 

If you pass everything, while on the level(s) that it's failing to farm, press ScreenCap button in Settings tab in the macro app. That will make 5 png images in the same folder as the executable. Send me cap_mode_4.
