### ISSUE TITLE
Wont select Events in the dimension gate wheel after last update.

### ISSUE THREAD

**Issue by Rainshadw** [yeetoverflow/autodisgaeaRPG#3]
Just sits there looking for the select event block. If I hit events and the block comes up it works fine... settings are what you suggest in the setup. Any ideas?
Many thanks. R

**Comment by yeetoverflow** [comment]
Dimension gate patterns were updated to fix this a few days ago. Do you have the most recent version?

**Comment by Rainshadw** [comment]
My apologies! Ill try that in a bit. My version is about a week old.
Probably just missed it!
