### ISSUE TITLE
Fight Then Pull Out not working properly

### ISSUE THREAD

**Issue by TheTonberryKinq** [yeetoverflow/autodisgaeaRPG#4]
As of 4/1 with the Overlord Priere raid, using the fightThenPullOut raid option does not continue after exiting the battle. Specifically, when farming the event stages and having fightThenPullOut selected as the raid behavior, it will enter the raid, exit, and then no longer continue. Previously the behavior would call for help after exiting the raid but this no longer occurs as well. The ideal fix would be for the fightThenPullOut behavior to enter the raid, exit the raid, call for help, and navigate back to the event stage selected to be farmed as it functioned previously. 

After exiting the raid, the status bar on the bottom will continue through Finding: raid.activeBoss → Finding: prompt.close. (1-7) → battle.done (1-2) and then loop. 

For reference, I am using the code from commit 59bb420 posted 3/31 on Bluestacks ver. 5.6.110.1002 N32.

**Comment by yeetoverflow** [comment]
@TheTonberryKinq Thanks for the info. Fix is live. Happy raiding.

**Comment by TheTonberryKinq** [comment]
> @TheTonberryKinq Thanks for the info. Fix is live. Happy raiding.

Thanks so much! I'd likely have quit the game if not for you releasing this - thank you for everything you've done and all the work you've put into it, it's seriously appreciated!
