### ISSUE TITLE
Guest companions aren't being chosen during story mode

### ISSUE THREAD

**Issue by ixanza** [yeetoverflow/autodisgaeaRPG#5]
Quite a few ttimes I've came back to my screen being stuck on choosing guest companions. I have the companions selection on 50pct and guest but it's never picked. 50pct selects both 30% and 50% companions for me fine. I'm running this on Nox Android 9 64bit

**Comment by yeetoverflow** [comment]
Create your own companion pattern. See [battle tutorial](https://youtu.be/GFgXBXYOiww) on how. You might need to create 2 patterns because there are 2 portrait sizes: initial and battle again (slightly smaller).
