### ISSUE TITLE
EventRaidLoop gets stuck for 50 tries before hitting Reload

### ISSUE THREAD

**Issue by maawolfe36** [yeetoverflow/autodisgaeaRPG#7]
I don't know if this is intentional or not, but when I am using this macro to run the event loop, if there are no raids to aid it gets stuck on Finding: raid.helper.1 and raid.helper.2 for 50 tries before it tries the Reload button. To me, 50 seems a little excessive because if there's no raids to help, sitting there for nearly a minute doesn't help anything. Is there any way to make this go a little faster, like maybe doing 10-20 tries before hitting refresh instead?

Here's a screenshot of what I mean, if that helps. You can see at the bottom it was on try 48, I took the screenshot a couple seconds early just to make sure I got it before it rolled over. Each try takes roughly a second, while the Reload button is available after about 4-5 tries. 
![Screenshot 2022-05-30 11 31 28](https://user-images.githubusercontent.com/103516755/171024156-815984f5-7f3b-4410-861e-777b71bfc199.png)

**Comment by yeetoverflow** [comment]
This isn't documented yet but there's an evenOptions.raid setting Next to the Raid label named Settings.eventOptions.raid.loopNumChecksBeforeRefresh. Try out and see if lower values work out for you.
![image](https://user-images.githubusercontent.com/93810758/171029953-2f8ad67c-7db2-4de6-b3a2-5ae799e7fb02.png)

**Comment by maawolfe36** [comment]
Thank you so much, that worked perfectly! I was wondering what that setting meant. I set it down to 15 and it's refreshing faster now. Thanks again, this macro is super useful and I appreciate the work you've done!
